DynestyStatic:
  search:
    bootstrap: null
    bound: multi
    enlarge: null
    facc: 0.2
    first_update: null
    fmove: 0.9
    max_move: 100
    nlive: 50
    sample: auto
    slices: 5
    update_interval: null
    walks: 5
  run:
    dlogz: null
    logl_max: .inf
    maxcall: null
    maxiter: null
    n_effective: null
  initialize:
    method: prior
  parallel:
    number_of_cores: 1
    force_x1_cpu: false
  printing:
    silence: false
DynestyDynamic:
  search:
    bootstrap: null
    bound: multi
    enlarge: null
    facc: 0.2
    first_update: null
    fmove: 0.9
    max_move: 100
    sample: auto
    slices: 5
    update_interval: null
    walks: 5
  run:
    dlogz_init: 0.01
    logl_max_init: .inf
    maxcall: null
    maxcall_init: null
    maxiter: null
    maxiter_init: null
    n_effective: .inf
    n_effective_init: .inf
    nlive_init: 500
  initialize:
    method: prior
  parallel:
    number_of_cores: 1
    force_x1_cpu: false
  printing:
    silence: false
